// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotificationsApi.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NotificationsApi.Migrations
{
    [DbContext(typeof(NotificationDbContext))]
    [Migration("20260411142349_SplitNotificationChannels")]
    partial class SplitNotificationChannels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("notification_service")
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NotificationsApi.Models.EmailNotificationDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RecipientEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("MessageId")
                        .IsUnique();

                    b.HasIndex("OrderId");

                    b.ToTable("EmailNotificationDeliveries", "notification_service");
                });

            modelBuilder.Entity("NotificationsApi.Models.NotificationUserProfile", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("EmailEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<bool>("SmsEnabled")
                        .HasColumnType("boolean");

                    b.HasKey("UserId");

                    b.ToTable("NotificationUsers", "notification_service");

                    b.HasData(
                        new
                        {
                            UserId = "demo-user-001",
                            Email = "demo.user.001@notifications.demo",
                            EmailEnabled = true,
                            PhoneNumber = "+15551000001",
                            SmsEnabled = true
                        },
                        new
                        {
                            UserId = "demo-user-002",
                            Email = "demo.user.002@notifications.demo",
                            EmailEnabled = true,
                            PhoneNumber = "+15551000002",
                            SmsEnabled = false
                        },
                        new
                        {
                            UserId = "demo-user-003",
                            Email = "demo.user.003@notifications.demo",
                            EmailEnabled = false,
                            PhoneNumber = "+15551000003",
                            SmsEnabled = true
                        },
                        new
                        {
                            UserId = "demo-user-004",
                            Email = "demo.user.004@notifications.demo",
                            EmailEnabled = true,
                            PhoneNumber = "+15551000004",
                            SmsEnabled = true
                        },
                        new
                        {
                            UserId = "demo-user-005",
                            Email = "demo.user.005@notifications.demo",
                            EmailEnabled = false,
                            PhoneNumber = "+15551000005",
                            SmsEnabled = false
                        },
                        new
                        {
                            UserId = "demo-user-006",
                            Email = "demo.user.006@notifications.demo",
                            EmailEnabled = true,
                            PhoneNumber = "+15551000006",
                            SmsEnabled = true
                        },
                        new
                        {
                            UserId = "demo-user-007",
                            Email = "demo.user.007@notifications.demo",
                            EmailEnabled = true,
                            PhoneNumber = "+15551000007",
                            SmsEnabled = false
                        },
                        new
                        {
                            UserId = "demo-user-008",
                            Email = "demo.user.008@notifications.demo",
                            EmailEnabled = false,
                            PhoneNumber = "+15551000008",
                            SmsEnabled = true
                        },
                        new
                        {
                            UserId = "demo-user-009",
                            Email = "demo.user.009@notifications.demo",
                            EmailEnabled = true,
                            PhoneNumber = "+15551000009",
                            SmsEnabled = true
                        },
                        new
                        {
                            UserId = "demo-user-123",
                            Email = "demo.user.123@notifications.demo",
                            EmailEnabled = true,
                            PhoneNumber = "+15551000123",
                            SmsEnabled = true
                        });
                });

            modelBuilder.Entity("NotificationsApi.Models.SmsNotificationDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RecipientPhoneNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("MessageId")
                        .IsUnique();

                    b.HasIndex("OrderId");

                    b.ToTable("SmsNotificationDeliveries", "notification_service");
                });
#pragma warning restore 612, 618
        }
    }
}
