<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>SerilogDemo.LogSearchTools</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\Tools\*.cs" Link="Tools\%(Filename)%(Extension)" />
  </ItemGroup>

</Project>
